### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by darkdarcool** [BD103/Starter-Templates#1]
Couple I think would be cool

- V8
- Blog
- React/Nextjs
- Java project
- Python library
ect.

**Comment by BD103** [comment]
Thanks! I have to split these up into separate repos because Github doesn't allow you to create a repo from a specific branch. Any suggestions for fixing this?

**Comment by darkdarcool** [comment]
No, the only solution I have is putting them in diff folders, otherwise I draw a blank
